apiVersion : apps/v1
kind: Deployment
metadata:
  name: jenkins       # Same name in AUTOSCALING scaleTargetRef 
  labels:
    app : jenkins
spec:
  selector:
    matchLabels:
      project: lol
  template:
    metadata:
      labels:
        project: lol   # Same name in SERVICE selector
    spec:
      containers:
        - name : jenkins
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 8080
            - containerPort: 50000

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: jenkins
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: jenkins
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    env  : staging
spec:
  selector:
    project: lol      # Name of project from DEPLOYMENT spec -> labels
  ports:
    - name      : wep-port
      protocol  : TCP
      port      : 8080
      targetPort: 8080  # Port on Pod
    - name      : config-port
      protocol  : TCP
      port      : 50000
      targetPort: 50000  # Port on Pod
  type: LoadBalancer
